#!/usr/bin/env bash
# this script should information about subdomains
func ()
{
	domain="$1"
	if [ "$2" ]
	then
		sub_d="$2"
	else
		sub_d="www lb-01 web-01 web-02"
	fi
	for su in $sub_d
	do
		echo -n "The subdomain $su"
		dig $su.$domain | grep -A1 "ANSWER SECTION:" | tail -n 1 | awk ' {print " is a " $4 " record and points to "$5}'
	done
}
func "$1" "$2"
