#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/404.html 
sudo chmod 777 /var/www/html/*
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www//html;
    index index.nginx-debian.html index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
