#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

sudo echo "http {
  ...
  include /etc/nginx/sites-enabled/*;
}" >> /etc/nginx/nginx.conf

sudo service nginx start
