#!/usr/bin/env bash
#Write a Bash script that:
#Creates the file /var/run/holbertonscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


echo $$ > /var/run/holbertonscript.pid

while :
do
trap "rm /var/run/holbertonscript.pid"  SIGTERM
trap "echo 'I hate the kill command'" SIGTERM

trap "echo 'Y U no love me?!'" SIGINT
trap  "rm /var/run/holbertonscript.pid" SIGQUIT
echo 'To infinity and beyond'

done
