#!/usr/bin/env bash
#manages manage_my_process
case $1 in
    start)
	echo $$ > /var/run/my_process.pid
	./manage_my_process &
	echo "manage_my_process started";;
    stop)
        pkill -SIGKILL -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped";;
    restart)
        pkill -SIGKILL -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	echo $$ > /var/run/my_process.pid
	./manage_my_process &
	echo "manage_my_process restarted";;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
esac