#!/usr/bin/env bash
# shellcheck disable=SC2009
#write a Bash script that displays lines containing the bash word,
#thus allowing you to easily get the PID of your Bash process.

ps auxf | grep -e "bash"
