#!/usr/bin/env bash
# This script is displaying Holberton School 10 times, but for the 9th iteration:
#displays Holberton School and then Hi on a new line.
x=1
while [ $x -le 10 ] 
do
    echo "Holberton School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    x=$(( x + 1 ))
done
