#!/usr/bin/env bash
# run nginx as nginx
sudo pkill apache
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
